"""Run the suite and let it draw itself.

    python tools/suite.py                 # fenced, the whole suite
    python tools/suite.py -m "not golden" # the fast half
    python tools/suite.py --unfenced      # when you mean to

**Why this exists.** A run that lives only in terminal scrollback has
said nothing by tomorrow. This one leaves `test/report.md` behind: what
ran, when, against which commit, whether the tree was clean, whether it
was fenced, and every failure named with its line. Extra arguments are
passed through to pytest.

**Why the report is not committed.** `pytest.ini` says it plainly — a
golden test re-renders through the interpreter and compares sample for
sample, and *"bit-exactness through `sin` and `exp` holds where the
buffer was made and nowhere else"*. A report is therefore a claim about
one machine at one commit. Committed, it would be read on a second
machine as though it meant something there, which is the exact drift
`doc/atlas/*.png` is kept out of the tree to avoid. So `test/report.md`
is generated, gitignored, and regenerated in about the time the suite
takes.

**It records the fence.** `tools/sandbox.sh` is where builds and tests
belong (`spec/sandbox.md`), and a report that did not say which side of
the fence it ran on would leave the reader to guess.
"""

import argparse
import re
import subprocess
import sys
import time
from datetime import datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
REPORT = ROOT / "test" / "report.md"


def _run(cmd, **kw):
    return subprocess.run(cmd, capture_output=True, text=True, cwd=ROOT, **kw)


def _commit():
    r = _run(["git", "log", "-1", "--format=%h %s"])
    return r.stdout.strip() or "(no commit)"


def _tree():
    r = _run(["git", "status", "--porcelain"])
    lines = [l for l in r.stdout.splitlines() if l.strip()]
    if not lines:
        return "clean"
    return f"{len(lines)} file(s) modified or untracked"


def _fence_state():
    """Ask the fence whether it is up, rather than assuming it."""
    r = _run([str(ROOT / "tools" / "sandbox.sh"), "--check"])
    ok = r.returncode == 0
    n = len(re.findall(r"[✓✗]", r.stdout))
    return ok, f"{n}/{n} — the fence is up" if ok else "FENCE INCOMPLETE"


# pytest -q prints, at the end, a line like:
#   3 failed, 2008 passed, 41 skipped, 2 warnings in 251.03s
TOTALS = re.compile(
    r"^(?:=+\s*)?((?:\d+ (?:passed|failed|error|errors|skipped|xfailed|xpassed|deselected|warnings?)"
    r"(?:, )?)+)(?: in [\d.]+s)?",
    re.M,
)
# --tb=line renders each failure as: /path/to/file.py:LINE: message
FAILLINE = re.compile(r"^(/\S+?\.py):(\d+):\s*(.*)$", re.M)
FAILNAME = re.compile(r"^(?:FAILED|ERROR)\s+(\S+)(?:\s+-\s+(.*))?$", re.M)


def main():
    ap = argparse.ArgumentParser(add_help=False)
    ap.add_argument("--unfenced", action="store_true")
    ap.add_argument("-h", "--help", action="store_true")
    args, passthrough = ap.parse_known_args()

    if args.help:
        print(__doc__)
        return 0

    pytest_cmd = [sys.executable, "-m", "pytest", "-q", "-p", "no:randomly",
                  "--tb=line", "-rfE", *passthrough]

    fenced = not args.unfenced
    fence_ok, fence_note = (None, "not asked")
    if fenced:
        fence_ok, fence_note = _fence_state()
        if not fence_ok:
            print("suite.py: the fence did not come up; refusing to claim it did.",
                  file=sys.stderr)
            print("          run tools/sandbox.sh --check, or pass --unfenced.",
                  file=sys.stderr)
            return 2
        cmd = [str(ROOT / "tools" / "sandbox.sh"), *pytest_cmd]
    else:
        cmd = pytest_cmd

    started = datetime.now()
    t0 = time.monotonic()
    proc = subprocess.run(cmd, cwd=ROOT, text=True,
                          stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
    wall = time.monotonic() - t0
    out = proc.stdout
    sys.stdout.write(out)

    totals = "(not parsed)"
    for m in TOTALS.finditer(out):
        totals = m.group(1).strip().rstrip(",")

    failures = []
    for name, why in FAILNAME.findall(out):
        failures.append((name, (why or "").strip()))
    if not failures:
        for path, line, msg in FAILLINE.findall(out):
            rel = Path(path).relative_to(ROOT) if str(path).startswith(str(ROOT)) else path
            failures.append((f"{rel}:{line}", msg.strip()))

    mins, secs = divmod(int(wall), 60)
    body = [
        "# test/report.md — the suite, as it last ran",
        "",
        "Generated by `tools/suite.py`.  **Not committed**, and `pytest.ini`",
        "says why: a golden test is bit-exact *where the buffer was made and",
        "nowhere else*, so this is a claim about one machine at one commit.",
        "Regenerate it rather than read an old one.",
        "",
        "| | |",
        "|---|---|",
        f"| Ran | {started:%Y-%m-%d %H:%M:%S} |",
        f"| Commit | `{_commit()}` |",
        f"| Tree | {_tree()} |",
        f"| Fence | {'`tools/sandbox.sh` — ' + fence_note if fenced else '**unfenced** (--unfenced)'} |",
        f"| Command | `{' '.join(pytest_cmd[1:])}` |",
        f"| Wall | {mins}m {secs}s |",
        f"| Exit | {proc.returncode} |",
        "",
        "## Totals",
        "",
        f"**{totals}**",
        "",
    ]

    if failures:
        body += [f"## The {len(failures)} that did not pass", ""]
        for name, why in failures:
            body.append(f"* `{name}`")
            if why:
                body.append(f"  * {why}")
        body += ["", "Full output is above in the terminal; this page keeps the names."]
    else:
        body += ["## Failures", "", "None.", ""]

    REPORT.parent.mkdir(parents=True, exist_ok=True)
    REPORT.write_text("\n".join(body) + "\n")
    print(f"\nsuite.py: drawn to {REPORT.relative_to(ROOT)}")
    return proc.returncode


if __name__ == "__main__":
    raise SystemExit(main())
